version: '3.9'
name: perplexity-api

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/status/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
