version: '3.9'
name: perplexity-api

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    healthcheck:
      test: curl --fail http://localhost:8000/api/status/ping || exit 1
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
